{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3fe7519b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: olefile in C:\\Users\\Sankar.Sasmal\\AppData\\Roaming\\Python\\Python311\\site-packages (0.47)\n",
      "Requirement already satisfied: xlrd in C:\\Users\\Sankar.Sasmal\\AppData\\Roaming\\Python\\Python311\\site-packages (2.0.2)\n",
      "Requirement already satisfied: pandas in C:\\Users\\Sankar.Sasmal\\AppData\\Roaming\\Python\\Python311\\site-packages (2.2.3)\n",
      "Requirement already satisfied: numpy>=1.23.2 in C:\\Users\\Sankar.Sasmal\\AppData\\Roaming\\Python\\Python311\\site-packages (from pandas) (2.2.4)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in C:\\Users\\Sankar.Sasmal\\AppData\\Roaming\\Python\\Python311\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in C:\\Users\\Sankar.Sasmal\\AppData\\Roaming\\Python\\Python311\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in C:\\Users\\Sankar.Sasmal\\AppData\\Roaming\\Python\\Python311\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: six>=1.5 in C:\\Users\\Sankar.Sasmal\\AppData\\Roaming\\Python\\Python311\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 26.2 -> 26.2.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "%pip install olefile xlrd pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "00154224",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "===========================================================================\n",
      "DHA CARBON DISTRIBUTION EXTRACTION\n",
      "===========================================================================\n",
      "Searching for .xls files under: C:\\Users\\Sankar.Sasmal\\OneDrive - Shell\\Desktop\\PuthonDashboard\\DHA\n",
      "Found 31 .xls file(s)\n",
      "\n",
      "[1/31] Processing: R17_C1_S1_001_2026-09-04 14-48-12 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_001\n",
      "  DateTime: 04/09/2026 14:48:12\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[2/31] Processing: R17_C1_S1_002_2026-09-04 17-59-51 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_002\n",
      "  DateTime: 04/09/2026 17:59:51\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[3/31] Processing: R17_C1_S1_003_2026-09-04 20-03-51 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_003\n",
      "  DateTime: 04/09/2026 20:03:51\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[4/31] Processing: R17_C1_S1_004_2026-09-04 22-07-54 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_004\n",
      "  DateTime: 04/09/2026 22:07:54\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[5/31] Processing: R17_C1_S1_005_2026-09-05 00-11-55 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_005\n",
      "  DateTime: 05/09/2026 00:11:55\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[6/31] Processing: R17_C1_S1_006_2026-09-05 02-15-51 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_006\n",
      "  DateTime: 05/09/2026 02:15:51\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[7/31] Processing: R17_C1_S1_007_2026-09-05 04-19-57 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_007\n",
      "  DateTime: 05/09/2026 04:19:57\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[8/31] Processing: R17_C1_S1_008_2026-09-05 06-23-55 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_008\n",
      "  DateTime: 05/09/2026 06:23:55\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[9/31] Processing: R17_C1_S1_009_2026-09-05 08-28-01 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_009\n",
      "  DateTime: 05/09/2026 08:28:01\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[10/31] Processing: R17_C1_S1_010_2026-09-05 10-32-03 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_010\n",
      "  DateTime: 05/09/2026 10:32:03\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[11/31] Processing: R17_C1_S1_011_2026-09-05 12-35-59 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_011\n",
      "  DateTime: 05/09/2026 12:35:59\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[12/31] Processing: R17_C1_S1_012_2026-09-05 14-40-01 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_012\n",
      "  DateTime: 05/09/2026 14:40:01\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[13/31] Processing: R17_C1_S1_013_2026-09-05 16-44-01 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_013\n",
      "  DateTime: 05/09/2026 16:44:01\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[14/31] Processing: R17_C1_S1_014_2026-09-05 18-48-07 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_014\n",
      "  DateTime: 05/09/2026 18:48:07\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[15/31] Processing: R17_C1_S1_015_2026-09-05 20-52-14 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_015\n",
      "  DateTime: 05/09/2026 20:52:14\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[16/31] Processing: R17_C1_S1_016_2026-09-05 22-56-09 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_016\n",
      "  DateTime: 05/09/2026 22:56:09\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[17/31] Processing: R17_C1_S1_017_2026-09-06 01-00-07 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_017\n",
      "  DateTime: 06/09/2026 01:00:07\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[18/31] Processing: R17_C1_S1_018_2026-09-06 03-04-13 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_018\n",
      "  DateTime: 06/09/2026 03:04:13\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[19/31] Processing: R17_C1_S1_019_2026-09-06 05-08-14 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_019\n",
      "  DateTime: 06/09/2026 05:08:14\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[20/31] Processing: R17_C1_S1_020_2026-09-06 07-12-12 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_020\n",
      "  DateTime: 06/09/2026 07:12:12\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[21/31] Processing: R17_C1_S1_021_2026-09-06 09-16-14 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_021\n",
      "  DateTime: 06/09/2026 09:16:14\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[22/31] Processing: R17_C1_S1_022_2026-09-06 11-20-16 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_022\n",
      "  DateTime: 06/09/2026 11:20:16\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[23/31] Processing: R17_C1_S1_023_2026-09-06 13-24-20 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_023\n",
      "  DateTime: 06/09/2026 13:24:20\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[24/31] Processing: R17_C1_S1_024_2026-09-06 15-28-22 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_024\n",
      "  DateTime: 06/09/2026 15:28:22\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[25/31] Processing: R17_C1_S1_025_2026-09-06 17-32-22 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_025\n",
      "  DateTime: 06/09/2026 17:32:22\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[26/31] Processing: R17_C1_S1_026_2026-09-06 19-36-20 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_026\n",
      "  DateTime: 06/09/2026 19:36:20\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[27/31] Processing: R17_C1_S1_027_2026-09-06 21-40-26 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_027\n",
      "  DateTime: 06/09/2026 21:40:26\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[28/31] Processing: R17_C1_S1_028_2026-09-06 23-44-27 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_028\n",
      "  DateTime: 06/09/2026 23:44:27\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[29/31] Processing: R17_C1_S1_029_2026-09-07 01-48-28 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_029\n",
      "  DateTime: 07/09/2026 01:48:28\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[30/31] Processing: R17_C1_S1_030_2026-09-07 03-52-30 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_030\n",
      "  DateTime: 07/09/2026 03:52:30\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "[31/31] Processing: R17_C1_S1_031_2026-09-07 05-56-31 (GMT +05-30)dat-Back Signal.XLS\n",
      "  UID: R17_C1_S1_031\n",
      "  DateTime: 07/09/2026 05:56:31\n",
      "  Carbon rows extracted: 15\n",
      "\n",
      "===========================================================================\n",
      "PROCESSING COMPLETED\n",
      "===========================================================================\n",
      "Total XLS files found : 31\n",
      "Successfully processed: 31\n",
      "Failed files          : 0\n",
      "\n",
      "HTML file created at:\n",
      "C:\\Users\\Sankar.Sasmal\\OneDrive - Shell\\Desktop\\PuthonDashboard\\DHA\\DHA_Carbon_Number_Stacked_Tables.html\n",
      "\n",
      "The HTML dashboard was opened in your default browser.\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "import webbrowser\n",
    "from datetime import datetime\n",
    "from pathlib import Path\n",
    "\n",
    "import olefile\n",
    "import xlrd\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 1. PROJECT AND FOLDER SETTINGS\n",
    "# ============================================================\n",
    "\n",
    "project_root = Path(\n",
    "    r\"C:\\Users\\Sankar.Sasmal\\OneDrive - Shell\\Desktop\\PuthonDashboard\"\n",
    ")\n",
    "\n",
    "configured_folder = project_root / \"NewDashboard\" / \"raw\" / \"DHA\"\n",
    "\n",
    "\n",
    "# Use the configured DHA folder if it exists.\n",
    "# Otherwise, search for the first folder named DHA.\n",
    "\n",
    "if configured_folder.is_dir():\n",
    "    folder_path = configured_folder\n",
    "\n",
    "else:\n",
    "    dha_folders = sorted(\n",
    "        path\n",
    "        for path in project_root.rglob(\"DHA\")\n",
    "        if path.is_dir()\n",
    "    )\n",
    "\n",
    "    folder_path = dha_folders[0] if dha_folders else project_root\n",
    "\n",
    "\n",
    "# Find all .xls files.\n",
    "# Ignore Excel temporary files that begin with ~$.\n",
    "\n",
    "if folder_path == project_root:\n",
    "    xls_files = sorted(\n",
    "        file_path\n",
    "        for file_path in project_root.rglob(\"*.xls\")\n",
    "        if not file_path.name.startswith(\"~$\")\n",
    "    )\n",
    "else:\n",
    "    xls_files = sorted(\n",
    "        file_path\n",
    "        for file_path in folder_path.glob(\"*.xls\")\n",
    "        if not file_path.name.startswith(\"~$\")\n",
    "    )\n",
    "\n",
    "\n",
    "print(\"=\" * 75)\n",
    "print(\"DHA CARBON DISTRIBUTION EXTRACTION\")\n",
    "print(\"=\" * 75)\n",
    "print(f\"Searching for .xls files under: {folder_path}\")\n",
    "print(f\"Found {len(xls_files)} .xls file(s)\")\n",
    "\n",
    "\n",
    "# Stop if no XLS files are found.\n",
    "\n",
    "if not xls_files:\n",
    "    raise FileNotFoundError(\n",
    "        f\"No .xls files were found under:\\n{folder_path}\"\n",
    "    )\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 2. DATETIME AND UID PATTERNS\n",
    "# ============================================================\n",
    "\n",
    "DT_PATTERN = re.compile(\n",
    "    r\"S1_\\d+_(\\d{4}-\\d{2}-\\d{2})\\s+\"\n",
    "    r\"(\\d{2})-(\\d{2})-(\\d{2})\"\n",
    ")\n",
    "\n",
    "UID_PATTERN = re.compile(\n",
    "    r\"([A-Za-z0-9]+_C\\d+_S\\d+_\\d+)_\"\n",
    "    r\"\\d{4}-\\d{2}-\\d{2}\"\n",
    ")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 3. WORKSHEET AND COMPONENT SETTINGS\n",
    "# ============================================================\n",
    "\n",
    "HEADER_SHEET = \"HEADER\"\n",
    "CARBON_SHEET = \"CARBON_TABULAR(%WGT)\"\n",
    "\n",
    "COMPONENTS = [\n",
    "    \"Paraffin\",\n",
    "    \"I-Paraffins\",\n",
    "    \"Aromatics\",\n",
    "    \"Naphthenes\",\n",
    "    \"Olefins\",\n",
    "]\n",
    "\n",
    "CARBON_NUMBERS = list(range(1, 16))\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 4. RESULT CONTAINERS\n",
    "# ============================================================\n",
    "\n",
    "metadata_results = []\n",
    "\n",
    "stacked_results = {\n",
    "    component: []\n",
    "    for component in COMPONENTS\n",
    "}\n",
    "\n",
    "processing_log = []\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 5. HELPER FUNCTION: CLEAN NUMERIC VALUES\n",
    "# ============================================================\n",
    "\n",
    "def clean_numeric_value(value):\n",
    "    \"\"\"\n",
    "    Convert an Excel cell value to a float.\n",
    "\n",
    "    Blank cells, '--', text markers, and other non-numeric\n",
    "    values are returned as pandas.NA.\n",
    "    \"\"\"\n",
    "\n",
    "    if value is None:\n",
    "        return pd.NA\n",
    "\n",
    "    if isinstance(value, str):\n",
    "        cleaned_value = value.strip()\n",
    "\n",
    "        missing_markers = {\n",
    "            \"\",\n",
    "            \"--\",\n",
    "            \"-\",\n",
    "            \"N/A\",\n",
    "            \"n/a\",\n",
    "            \"NA\",\n",
    "            \"na\",\n",
    "            \"None\",\n",
    "        }\n",
    "\n",
    "        if cleaned_value in missing_markers:\n",
    "            return pd.NA\n",
    "\n",
    "        try:\n",
    "            return float(cleaned_value)\n",
    "\n",
    "        except ValueError:\n",
    "            return pd.NA\n",
    "\n",
    "    try:\n",
    "        return float(value)\n",
    "\n",
    "    except (TypeError, ValueError):\n",
    "        return pd.NA\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 6. HELPER FUNCTION: NORMALIZE HEADERS\n",
    "# ============================================================\n",
    "\n",
    "def normalize_header(value):\n",
    "    \"\"\"\n",
    "    Normalize possible variations in the headers appearing\n",
    "    in Excel cells C3:H3.\n",
    "    \"\"\"\n",
    "\n",
    "    header = str(value).strip()\n",
    "\n",
    "    header_mapping = {\n",
    "        \"CARBON #\": \"CARBON#\",\n",
    "        \"Carbon#\": \"CARBON#\",\n",
    "        \"Carbon #\": \"CARBON#\",\n",
    "        \"carbon#\": \"CARBON#\",\n",
    "        \"carbon #\": \"CARBON#\",\n",
    "        \"CARBON\": \"CARBON#\",\n",
    "\n",
    "        \"Paraffins\": \"Paraffin\",\n",
    "        \"paraffin\": \"Paraffin\",\n",
    "        \"paraffins\": \"Paraffin\",\n",
    "\n",
    "        \"I-Paraffin\": \"I-Paraffins\",\n",
    "        \"i-Paraffin\": \"I-Paraffins\",\n",
    "        \"i-Paraffins\": \"I-Paraffins\",\n",
    "        \"Iso-Paraffin\": \"I-Paraffins\",\n",
    "        \"Iso-Paraffins\": \"I-Paraffins\",\n",
    "\n",
    "        \"Aromatic\": \"Aromatics\",\n",
    "        \"aromatic\": \"Aromatics\",\n",
    "        \"aromatics\": \"Aromatics\",\n",
    "\n",
    "        \"Naphthene\": \"Naphthenes\",\n",
    "        \"naphthene\": \"Naphthenes\",\n",
    "        \"naphthenes\": \"Naphthenes\",\n",
    "\n",
    "        \"Olefin\": \"Olefins\",\n",
    "        \"olefin\": \"Olefins\",\n",
    "        \"olefins\": \"Olefins\",\n",
    "    }\n",
    "\n",
    "    return header_mapping.get(header, header)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 7. HELPER FUNCTION: OPEN XLS WORKBOOK\n",
    "# ============================================================\n",
    "\n",
    "def open_xls_workbook(file_path):\n",
    "    \"\"\"\n",
    "    Open the XLS workbook using its OLE Workbook stream.\n",
    "\n",
    "    This follows the same method as the existing working code\n",
    "    and uses ignore_workbook_corruption=True.\n",
    "    \"\"\"\n",
    "\n",
    "    with olefile.OleFileIO(str(file_path)) as ole:\n",
    "\n",
    "        if ole.exists(\"Workbook\"):\n",
    "            stream_name = \"Workbook\"\n",
    "\n",
    "        elif ole.exists(\"Book\"):\n",
    "            stream_name = \"Book\"\n",
    "\n",
    "        else:\n",
    "            raise ValueError(\n",
    "                \"Neither the 'Workbook' nor the 'Book' \"\n",
    "                \"OLE stream was found.\"\n",
    "            )\n",
    "\n",
    "        biff_data = ole.openstream(stream_name).read()\n",
    "\n",
    "    workbook = xlrd.open_workbook(\n",
    "        file_contents=biff_data,\n",
    "        ignore_workbook_corruption=True,\n",
    "    )\n",
    "\n",
    "    return workbook\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 8. HELPER FUNCTION: EXTRACT METADATA\n",
    "# ============================================================\n",
    "\n",
    "def extract_metadata(workbook):\n",
    "    \"\"\"\n",
    "    Extract UID and DateTime from HEADER!B6.\n",
    "\n",
    "    xlrd uses zero-based indexing:\n",
    "        Row index 5, column index 1 = Excel cell B6.\n",
    "    \"\"\"\n",
    "\n",
    "    if HEADER_SHEET not in workbook.sheet_names():\n",
    "        raise ValueError(\n",
    "            f\"Worksheet '{HEADER_SHEET}' was not found.\"\n",
    "        )\n",
    "\n",
    "    header_sheet = workbook.sheet_by_name(HEADER_SHEET)\n",
    "\n",
    "    if header_sheet.nrows < 6 or header_sheet.ncols < 2:\n",
    "        raise ValueError(\n",
    "            \"The HEADER worksheet does not contain cell B6.\"\n",
    "        )\n",
    "\n",
    "    b6_value = str(\n",
    "        header_sheet.cell_value(5, 1)\n",
    "    ).strip()\n",
    "\n",
    "    # Extract DateTime\n",
    "\n",
    "    date_match = DT_PATTERN.search(b6_value)\n",
    "\n",
    "    if not date_match:\n",
    "        raise ValueError(\n",
    "            f\"Date/time pattern was not found in \"\n",
    "            f\"HEADER!B6: {b6_value!r}\"\n",
    "        )\n",
    "\n",
    "    date_str, hour, minute, second = date_match.groups()\n",
    "\n",
    "    analysis_datetime = datetime.strptime(\n",
    "        f\"{date_str} {hour}:{minute}:{second}\",\n",
    "        \"%Y-%m-%d %H:%M:%S\",\n",
    "    )\n",
    "\n",
    "    # Extract UID\n",
    "\n",
    "    uid_match = UID_PATTERN.search(b6_value)\n",
    "\n",
    "    if not uid_match:\n",
    "        raise ValueError(\n",
    "            f\"UID pattern was not found in \"\n",
    "            f\"HEADER!B6: {b6_value!r}\"\n",
    "        )\n",
    "\n",
    "    uid = uid_match.group(1)\n",
    "\n",
    "    return b6_value, analysis_datetime, uid\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 9. HELPER FUNCTION: EXTRACT CARBON TABLE\n",
    "# ============================================================\n",
    "\n",
    "def extract_carbon_table(workbook):\n",
    "    \"\"\"\n",
    "    Extract the following Excel range:\n",
    "\n",
    "        CARBON_TABULAR(%WGT)!C3:H18\n",
    "\n",
    "    Structure expected:\n",
    "\n",
    "        C3 = CARBON#\n",
    "        D3 = Paraffin\n",
    "        E3 = I-Paraffins\n",
    "        F3 = Aromatics\n",
    "        G3 = Naphthenes\n",
    "        H3 = Olefins\n",
    "\n",
    "        Rows 4 to 18 = Carbon numbers 1 to 15\n",
    "\n",
    "    xlrd uses zero-based indexing:\n",
    "        C = column index 2\n",
    "        H = column index 7\n",
    "        Row 3 = row index 2\n",
    "        Row 18 = row index 17\n",
    "    \"\"\"\n",
    "\n",
    "    if CARBON_SHEET not in workbook.sheet_names():\n",
    "        raise ValueError(\n",
    "            f\"Worksheet '{CARBON_SHEET}' was not found.\"\n",
    "        )\n",
    "\n",
    "    carbon_sheet = workbook.sheet_by_name(CARBON_SHEET)\n",
    "\n",
    "    if carbon_sheet.nrows < 18:\n",
    "        raise ValueError(\n",
    "            f\"Worksheet '{CARBON_SHEET}' has only \"\n",
    "            f\"{carbon_sheet.nrows} rows. \"\n",
    "            \"The required range extends to row 18.\"\n",
    "        )\n",
    "\n",
    "    if carbon_sheet.ncols < 8:\n",
    "        raise ValueError(\n",
    "            f\"Worksheet '{CARBON_SHEET}' has only \"\n",
    "            f\"{carbon_sheet.ncols} columns. \"\n",
    "            \"The required range extends to column H.\"\n",
    "        )\n",
    "\n",
    "    # Read the headers from C3:H3.\n",
    "\n",
    "    headers = [\n",
    "        normalize_header(\n",
    "            carbon_sheet.cell_value(2, column_index)\n",
    "        )\n",
    "        for column_index in range(2, 8)\n",
    "    ]\n",
    "\n",
    "    expected_headers = [\n",
    "        \"CARBON#\",\n",
    "        \"Paraffin\",\n",
    "        \"I-Paraffins\",\n",
    "        \"Aromatics\",\n",
    "        \"Naphthenes\",\n",
    "        \"Olefins\",\n",
    "    ]\n",
    "\n",
    "    missing_headers = [\n",
    "        header\n",
    "        for header in expected_headers\n",
    "        if header not in headers\n",
    "    ]\n",
    "\n",
    "    if missing_headers:\n",
    "        raise ValueError(\n",
    "            f\"Missing header(s) in C3:H3: {missing_headers}. \"\n",
    "            f\"Headers found: {headers}\"\n",
    "        )\n",
    "\n",
    "    # Map component names to actual worksheet column indexes.\n",
    "\n",
    "    header_to_column = {\n",
    "        header: column_index\n",
    "        for header, column_index in zip(\n",
    "            headers,\n",
    "            range(2, 8),\n",
    "        )\n",
    "    }\n",
    "\n",
    "    carbon_records = []\n",
    "\n",
    "    # Read rows 4 to 18.\n",
    "    # xlrd indexes are 3 through 17.\n",
    "\n",
    "    for row_index in range(3, 18):\n",
    "\n",
    "        carbon_raw = carbon_sheet.cell_value(\n",
    "            row_index,\n",
    "            header_to_column[\"CARBON#\"],\n",
    "        )\n",
    "\n",
    "        carbon_numeric = clean_numeric_value(carbon_raw)\n",
    "\n",
    "        if pd.isna(carbon_numeric):\n",
    "            continue\n",
    "\n",
    "        carbon_number = int(carbon_numeric)\n",
    "\n",
    "        if carbon_number not in CARBON_NUMBERS:\n",
    "            continue\n",
    "\n",
    "        record = {\n",
    "            \"CARBON#\": carbon_number,\n",
    "        }\n",
    "\n",
    "        for component in COMPONENTS:\n",
    "\n",
    "            raw_value = carbon_sheet.cell_value(\n",
    "                row_index,\n",
    "                header_to_column[component],\n",
    "            )\n",
    "\n",
    "            record[component] = clean_numeric_value(\n",
    "                raw_value\n",
    "            )\n",
    "\n",
    "        carbon_records.append(record)\n",
    "\n",
    "    carbon_df = pd.DataFrame(\n",
    "        carbon_records,\n",
    "        columns=[\"CARBON#\"] + COMPONENTS,\n",
    "    )\n",
    "\n",
    "    return carbon_df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 10. PROCESS EVERY XLS FILE\n",
    "# ============================================================\n",
    "\n",
    "for file_number, file_path in enumerate(\n",
    "    xls_files,\n",
    "    start=1,\n",
    "):\n",
    "    file_name = file_path.name\n",
    "\n",
    "    print()\n",
    "    print(\n",
    "        f\"[{file_number}/{len(xls_files)}] \"\n",
    "        f\"Processing: {file_name}\"\n",
    "    )\n",
    "\n",
    "    try:\n",
    "        # Open the XLS file only once.\n",
    "\n",
    "        workbook = open_xls_workbook(file_path)\n",
    "\n",
    "        # Extract UID and DateTime from HEADER!B6.\n",
    "\n",
    "        (\n",
    "            b6_value,\n",
    "            analysis_datetime,\n",
    "            uid,\n",
    "        ) = extract_metadata(workbook)\n",
    "\n",
    "        # Extract C3:H18 from CARBON_TABULAR(%WGT).\n",
    "\n",
    "        carbon_df = extract_carbon_table(workbook)\n",
    "\n",
    "        # Store metadata.\n",
    "\n",
    "        metadata_results.append(\n",
    "            {\n",
    "                \"File Name\": file_name,\n",
    "                \"DateTime\": analysis_datetime,\n",
    "                \"UID\": uid,\n",
    "                \"HEADER B6\": b6_value,\n",
    "            }\n",
    "        )\n",
    "\n",
    "        # Create one row per XLS file for each hydrocarbon class.\n",
    "        # CARBON# values 1 to 15 become columns.\n",
    "\n",
    "        for component in COMPONENTS:\n",
    "\n",
    "            output_row = {\n",
    "                \"File Name\": file_name,\n",
    "                \"DateTime\": analysis_datetime,\n",
    "                \"UID\": uid,\n",
    "            }\n",
    "\n",
    "            # Initialize C1 to C15 as missing values.\n",
    "\n",
    "            for carbon_number in CARBON_NUMBERS:\n",
    "                output_row[carbon_number] = pd.NA\n",
    "\n",
    "            # Populate the component values.\n",
    "\n",
    "            for _, carbon_row in carbon_df.iterrows():\n",
    "\n",
    "                carbon_number = int(\n",
    "                    carbon_row[\"CARBON#\"]\n",
    "                )\n",
    "\n",
    "                output_row[carbon_number] = (\n",
    "                    carbon_row[component]\n",
    "                )\n",
    "\n",
    "            stacked_results[component].append(\n",
    "                output_row\n",
    "            )\n",
    "\n",
    "        processing_log.append(\n",
    "            {\n",
    "                \"File Name\": file_name,\n",
    "                \"Status\": \"Success\",\n",
    "                \"UID\": uid,\n",
    "                \"Message\": \"\",\n",
    "            }\n",
    "        )\n",
    "\n",
    "        print(f\"  UID: {uid}\")\n",
    "        print(\n",
    "            \"  DateTime: \"\n",
    "            f\"{analysis_datetime:%d/%m/%Y %H:%M:%S}\"\n",
    "        )\n",
    "        print(\n",
    "            f\"  Carbon rows extracted: {len(carbon_df)}\"\n",
    "        )\n",
    "\n",
    "    except Exception as error:\n",
    "\n",
    "        error_message = str(error)\n",
    "\n",
    "        metadata_results.append(\n",
    "            {\n",
    "                \"File Name\": file_name,\n",
    "                \"DateTime\": pd.NaT,\n",
    "                \"UID\": \"\",\n",
    "                \"HEADER B6\": \"\",\n",
    "            }\n",
    "        )\n",
    "\n",
    "        processing_log.append(\n",
    "            {\n",
    "                \"File Name\": file_name,\n",
    "                \"Status\": \"Failed\",\n",
    "                \"UID\": \"\",\n",
    "                \"Message\": error_message,\n",
    "            }\n",
    "        )\n",
    "\n",
    "        print(f\"  Failed: {error_message}\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 11. CREATE METADATA DATAFRAME\n",
    "# ============================================================\n",
    "\n",
    "metadata_df = pd.DataFrame(\n",
    "    metadata_results,\n",
    "    columns=[\n",
    "        \"File Name\",\n",
    "        \"DateTime\",\n",
    "        \"UID\",\n",
    "        \"HEADER B6\",\n",
    "    ],\n",
    ")\n",
    "\n",
    "if not metadata_df.empty:\n",
    "    metadata_df = (\n",
    "        metadata_df\n",
    "        .sort_values(\n",
    "            by=[\"DateTime\", \"File Name\"],\n",
    "            na_position=\"last\",\n",
    "        )\n",
    "        .reset_index(drop=True)\n",
    "    )\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 12. CREATE THE FIVE COMPONENT DATAFRAMES\n",
    "# ============================================================\n",
    "\n",
    "final_column_order = [\n",
    "    \"File Name\",\n",
    "    \"DateTime\",\n",
    "    \"UID\",\n",
    "] + CARBON_NUMBERS\n",
    "\n",
    "component_tables = {}\n",
    "\n",
    "for component in COMPONENTS:\n",
    "\n",
    "    component_df = pd.DataFrame(\n",
    "        stacked_results[component],\n",
    "        columns=final_column_order,\n",
    "    )\n",
    "\n",
    "    if not component_df.empty:\n",
    "\n",
    "        component_df = (\n",
    "            component_df\n",
    "            .sort_values(\n",
    "                by=[\"DateTime\", \"File Name\"],\n",
    "                na_position=\"last\",\n",
    "            )\n",
    "            .reset_index(drop=True)\n",
    "        )\n",
    "\n",
    "        # Display DateTime in the required format.\n",
    "\n",
    "        component_df[\"DateTime\"] = (\n",
    "            pd.to_datetime(\n",
    "                component_df[\"DateTime\"],\n",
    "                errors=\"coerce\",\n",
    "            )\n",
    "            .dt.strftime(\"%d/%m/%Y %H:%M\")\n",
    "        )\n",
    "\n",
    "        component_df[\"DateTime\"] = (\n",
    "            component_df[\"DateTime\"]\n",
    "            .fillna(\"\")\n",
    "        )\n",
    "\n",
    "    component_tables[component] = component_df\n",
    "\n",
    "\n",
    "# Optional individual variables for later use.\n",
    "\n",
    "paraffin_table = component_tables[\"Paraffin\"]\n",
    "i_paraffins_table = component_tables[\"I-Paraffins\"]\n",
    "aromatics_table = component_tables[\"Aromatics\"]\n",
    "naphthenes_table = component_tables[\"Naphthenes\"]\n",
    "olefins_table = component_tables[\"Olefins\"]\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 13. CREATE PROCESSING LOG DATAFRAME\n",
    "# ============================================================\n",
    "\n",
    "processing_log_df = pd.DataFrame(\n",
    "    processing_log,\n",
    "    columns=[\n",
    "        \"File Name\",\n",
    "        \"Status\",\n",
    "        \"UID\",\n",
    "        \"Message\",\n",
    "    ],\n",
    ")\n",
    "\n",
    "if not processing_log_df.empty:\n",
    "    processing_log_df = (\n",
    "        processing_log_df\n",
    "        .sort_values(\"File Name\")\n",
    "        .reset_index(drop=True)\n",
    "    )\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 14. FORMAT COMPONENT TABLES AS HTML\n",
    "# ============================================================\n",
    "\n",
    "tables_html = {}\n",
    "\n",
    "for component, component_df in component_tables.items():\n",
    "\n",
    "    safe_table_id = (\n",
    "        component\n",
    "        .lower()\n",
    "        .replace(\"-\", \"_\")\n",
    "        .replace(\" \", \"_\")\n",
    "    )\n",
    "\n",
    "    tables_html[component] = component_df.to_html(\n",
    "        index=False,\n",
    "        border=0,\n",
    "        classes=\"data-table\",\n",
    "        table_id=f\"table_{safe_table_id}\",\n",
    "        na_rep=\"\",\n",
    "        float_format=lambda value: f\"{value:.6f}\",\n",
    "    )\n",
    "\n",
    "\n",
    "# Create metadata table for the details tab.\n",
    "\n",
    "metadata_display_df = metadata_df.copy()\n",
    "\n",
    "if not metadata_display_df.empty:\n",
    "\n",
    "    metadata_display_df[\"DateTime\"] = (\n",
    "        pd.to_datetime(\n",
    "            metadata_display_df[\"DateTime\"],\n",
    "            errors=\"coerce\",\n",
    "        )\n",
    "        .dt.strftime(\"%d/%m/%Y %H:%M\")\n",
    "        .fillna(\"\")\n",
    "    )\n",
    "\n",
    "metadata_html = metadata_display_df.to_html(\n",
    "    index=False,\n",
    "    border=0,\n",
    "    classes=\"data-table\",\n",
    "    table_id=\"metadata_table\",\n",
    "    na_rep=\"\",\n",
    ")\n",
    "\n",
    "\n",
    "# Create processing-log HTML.\n",
    "\n",
    "processing_log_html = processing_log_df.to_html(\n",
    "    index=False,\n",
    "    border=0,\n",
    "    classes=\"data-table\",\n",
    "    table_id=\"processing_log_table\",\n",
    "    na_rep=\"\",\n",
    ")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 15. CREATE THE COMPLETE HTML DASHBOARD\n",
    "# ============================================================\n",
    "\n",
    "html_file = (\n",
    "    folder_path\n",
    "    / \"DHA_Carbon_Number_Stacked_Tables.html\"\n",
    ")\n",
    "\n",
    "\n",
    "html_content = f\"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"en\">\n",
    "\n",
    "<head>\n",
    "\n",
    "    <meta charset=\"UTF-8\">\n",
    "\n",
    "    <meta\n",
    "        name=\"viewport\"\n",
    "        content=\"width=device-width, initial-scale=1.0\"\n",
    "    >\n",
    "\n",
    "    <title>DHA Carbon Distribution Dashboard</title>\n",
    "\n",
    "    <style>\n",
    "\n",
    "        * {{\n",
    "            box-sizing: border-box;\n",
    "        }}\n",
    "\n",
    "        body {{\n",
    "            margin: 0;\n",
    "            padding: 24px;\n",
    "            background-color: #f4f6f8;\n",
    "            color: #263238;\n",
    "            font-family: Arial, Helvetica, sans-serif;\n",
    "        }}\n",
    "\n",
    "        .dashboard-container {{\n",
    "            max-width: 1800px;\n",
    "            margin: 0 auto;\n",
    "        }}\n",
    "\n",
    "        .header-card {{\n",
    "            padding: 24px;\n",
    "            margin-bottom: 20px;\n",
    "            border-radius: 12px;\n",
    "            background: linear-gradient(\n",
    "                135deg,\n",
    "                #003c71,\n",
    "                #0078a8\n",
    "            );\n",
    "            color: white;\n",
    "            box-shadow: 0 4px 14px rgba(0, 0, 0, 0.12);\n",
    "        }}\n",
    "\n",
    "        .header-card h1 {{\n",
    "            margin: 0 0 8px 0;\n",
    "            font-size: 28px;\n",
    "        }}\n",
    "\n",
    "        .header-card p {{\n",
    "            margin: 0;\n",
    "            color: #e2f3fb;\n",
    "            font-size: 14px;\n",
    "        }}\n",
    "\n",
    "        .summary-grid {{\n",
    "            display: grid;\n",
    "            grid-template-columns: repeat(\n",
    "                auto-fit,\n",
    "                minmax(180px, 1fr)\n",
    "            );\n",
    "            gap: 15px;\n",
    "            margin-bottom: 20px;\n",
    "        }}\n",
    "\n",
    "        .summary-card {{\n",
    "            padding: 18px;\n",
    "            border-radius: 10px;\n",
    "            background: white;\n",
    "            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);\n",
    "        }}\n",
    "\n",
    "        .summary-label {{\n",
    "            margin-bottom: 6px;\n",
    "            color: #607d8b;\n",
    "            font-size: 13px;\n",
    "        }}\n",
    "\n",
    "        .summary-value {{\n",
    "            color: #003c71;\n",
    "            font-size: 24px;\n",
    "            font-weight: bold;\n",
    "        }}\n",
    "\n",
    "        .control-panel {{\n",
    "            display: flex;\n",
    "            flex-wrap: wrap;\n",
    "            align-items: flex-end;\n",
    "            gap: 18px;\n",
    "            padding: 20px;\n",
    "            margin-bottom: 20px;\n",
    "            border-radius: 10px;\n",
    "            background-color: white;\n",
    "            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);\n",
    "        }}\n",
    "\n",
    "        .control-group {{\n",
    "            display: flex;\n",
    "            flex-direction: column;\n",
    "            gap: 7px;\n",
    "        }}\n",
    "\n",
    "        .control-group label {{\n",
    "            color: #455a64;\n",
    "            font-size: 13px;\n",
    "            font-weight: bold;\n",
    "        }}\n",
    "\n",
    "        select,\n",
    "        input {{\n",
    "            min-width: 230px;\n",
    "            padding: 10px 12px;\n",
    "            border: 1px solid #bcc7cd;\n",
    "            border-radius: 6px;\n",
    "            background-color: white;\n",
    "            font-size: 14px;\n",
    "            outline: none;\n",
    "        }}\n",
    "\n",
    "        select:focus,\n",
    "        input:focus {{\n",
    "            border-color: #0078a8;\n",
    "            box-shadow: 0 0 0 3px rgba(0, 120, 168, 0.12);\n",
    "        }}\n",
    "\n",
    "        button {{\n",
    "            padding: 10px 18px;\n",
    "            border: none;\n",
    "            border-radius: 6px;\n",
    "            background-color: #0078a8;\n",
    "            color: white;\n",
    "            cursor: pointer;\n",
    "            font-size: 14px;\n",
    "            font-weight: bold;\n",
    "        }}\n",
    "\n",
    "        button:hover {{\n",
    "            background-color: #005f86;\n",
    "        }}\n",
    "\n",
    "        .content-card {{\n",
    "            overflow: hidden;\n",
    "            border-radius: 10px;\n",
    "            background-color: white;\n",
    "            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);\n",
    "        }}\n",
    "\n",
    "        .table-title {{\n",
    "            display: flex;\n",
    "            flex-wrap: wrap;\n",
    "            align-items: center;\n",
    "            justify-content: space-between;\n",
    "            gap: 10px;\n",
    "            padding: 16px 20px;\n",
    "            border-bottom: 1px solid #dfe5e8;\n",
    "        }}\n",
    "\n",
    "        .table-title h2 {{\n",
    "            margin: 0;\n",
    "            color: #003c71;\n",
    "            font-size: 19px;\n",
    "        }}\n",
    "\n",
    "        .table-counter {{\n",
    "            color: #607d8b;\n",
    "            font-size: 13px;\n",
    "        }}\n",
    "\n",
    "        .table-scroll {{\n",
    "            overflow-x: auto;\n",
    "            max-height: 70vh;\n",
    "            overflow-y: auto;\n",
    "        }}\n",
    "\n",
    "        .table-container {{\n",
    "            display: none;\n",
    "        }}\n",
    "\n",
    "        .table-container.active {{\n",
    "            display: block;\n",
    "        }}\n",
    "\n",
    "        table.data-table {{\n",
    "            width: 100%;\n",
    "            min-width: 1400px;\n",
    "            border-collapse: separate;\n",
    "            border-spacing: 0;\n",
    "            background-color: white;\n",
    "            font-size: 13px;\n",
    "        }}\n",
    "\n",
    "        table.data-table thead th {{\n",
    "            position: sticky;\n",
    "            top: 0;\n",
    "            z-index: 2;\n",
    "            padding: 11px 10px;\n",
    "            border-right: 1px solid #376b93;\n",
    "            border-bottom: 1px solid #376b93;\n",
    "            background-color: #1f4e78;\n",
    "            color: white;\n",
    "            text-align: center;\n",
    "            white-space: nowrap;\n",
    "        }}\n",
    "\n",
    "        table.data-table tbody td {{\n",
    "            padding: 9px 10px;\n",
    "            border-right: 1px solid #e0e5e8;\n",
    "            border-bottom: 1px solid #e0e5e8;\n",
    "            text-align: right;\n",
    "            white-space: nowrap;\n",
    "        }}\n",
    "\n",
    "        table.data-table tbody td:nth-child(1),\n",
    "        table.data-table tbody td:nth-child(2),\n",
    "        table.data-table tbody td:nth-child(3) {{\n",
    "            text-align: left;\n",
    "        }}\n",
    "\n",
    "        table.data-table tbody tr:nth-child(even) {{\n",
    "            background-color: #f8fafb;\n",
    "        }}\n",
    "\n",
    "        table.data-table tbody tr:hover {{\n",
    "            background-color: #e8f5fb;\n",
    "        }}\n",
    "\n",
    "        .hidden-row {{\n",
    "            display: none;\n",
    "        }}\n",
    "\n",
    "        .message {{\n",
    "            display: none;\n",
    "            padding: 25px;\n",
    "            color: #607d8b;\n",
    "            text-align: center;\n",
    "        }}\n",
    "\n",
    "        .message.visible {{\n",
    "            display: block;\n",
    "        }}\n",
    "\n",
    "        .footer {{\n",
    "            padding: 18px 5px;\n",
    "            color: #78909c;\n",
    "            font-size: 12px;\n",
    "            text-align: center;\n",
    "        }}\n",
    "\n",
    "        @media (max-width: 700px) {{\n",
    "\n",
    "            body {{\n",
    "                padding: 12px;\n",
    "            }}\n",
    "\n",
    "            .header-card {{\n",
    "                padding: 18px;\n",
    "            }}\n",
    "\n",
    "            .header-card h1 {{\n",
    "                font-size: 22px;\n",
    "            }}\n",
    "\n",
    "            .control-panel {{\n",
    "                align-items: stretch;\n",
    "            }}\n",
    "\n",
    "            .control-group,\n",
    "            select,\n",
    "            input,\n",
    "            button {{\n",
    "                width: 100%;\n",
    "                min-width: 100%;\n",
    "            }}\n",
    "        }}\n",
    "\n",
    "    </style>\n",
    "\n",
    "</head>\n",
    "\n",
    "<body>\n",
    "\n",
    "    <div class=\"dashboard-container\">\n",
    "\n",
    "        <div class=\"header-card\">\n",
    "\n",
    "            <h1>DHA Carbon Distribution Dashboard</h1>\n",
    "\n",
    "            <p>\n",
    "                Carbon number distribution extracted from\n",
    "                CARBON_TABULAR(%WGT), range C3:H18\n",
    "            </p>\n",
    "\n",
    "        </div>\n",
    "\n",
    "\n",
    "        <div class=\"summary-grid\">\n",
    "\n",
    "            <div class=\"summary-card\">\n",
    "\n",
    "                <div class=\"summary-label\">\n",
    "                    XLS files found\n",
    "                </div>\n",
    "\n",
    "                <div class=\"summary-value\">\n",
    "                    {len(xls_files)}\n",
    "                </div>\n",
    "\n",
    "            </div>\n",
    "\n",
    "\n",
    "            <div class=\"summary-card\">\n",
    "\n",
    "                <div class=\"summary-label\">\n",
    "                    Successfully processed\n",
    "                </div>\n",
    "\n",
    "                <div class=\"summary-value\">\n",
    "                    {\n",
    "                        int(\n",
    "                            processing_log_df[\"Status\"]\n",
    "                            .eq(\"Success\")\n",
    "                            .sum()\n",
    "                        )\n",
    "                        if not processing_log_df.empty\n",
    "                        else 0\n",
    "                    }\n",
    "                </div>\n",
    "\n",
    "            </div>\n",
    "\n",
    "\n",
    "            <div class=\"summary-card\">\n",
    "\n",
    "                <div class=\"summary-label\">\n",
    "                    Failed files\n",
    "                </div>\n",
    "\n",
    "                <div class=\"summary-value\">\n",
    "                    {\n",
    "                        int(\n",
    "                            processing_log_df[\"Status\"]\n",
    "                            .eq(\"Failed\")\n",
    "                            .sum()\n",
    "                        )\n",
    "                        if not processing_log_df.empty\n",
    "                        else 0\n",
    "                    }\n",
    "                </div>\n",
    "\n",
    "            </div>\n",
    "\n",
    "\n",
    "            <div class=\"summary-card\">\n",
    "\n",
    "                <div class=\"summary-label\">\n",
    "                    Carbon range\n",
    "                </div>\n",
    "\n",
    "                <div class=\"summary-value\">\n",
    "                    C1-C15\n",
    "                </div>\n",
    "\n",
    "            </div>\n",
    "\n",
    "        </div>\n",
    "\n",
    "\n",
    "        <div class=\"control-panel\">\n",
    "\n",
    "            <div class=\"control-group\">\n",
    "\n",
    "                <label for=\"componentSelector\">\n",
    "                    Select component\n",
    "                </label>\n",
    "\n",
    "                <select id=\"componentSelector\">\n",
    "\n",
    "                    <option value=\"Paraffin\">\n",
    "                        Paraffin\n",
    "                    </option>\n",
    "\n",
    "                    <option value=\"I-Paraffins\">\n",
    "                        I-Paraffins\n",
    "                    </option>\n",
    "\n",
    "                    <option value=\"Aromatics\">\n",
    "                        Aromatics\n",
    "                    </option>\n",
    "\n",
    "                    <option value=\"Naphthenes\">\n",
    "                        Naphthenes\n",
    "                    </option>\n",
    "\n",
    "                    <option value=\"Olefins\">\n",
    "                        Olefins\n",
    "                    </option>\n",
    "\n",
    "                    <option value=\"Metadata\">\n",
    "                        Metadata\n",
    "                    </option>\n",
    "\n",
    "                    <option value=\"Processing-Log\">\n",
    "                        Processing Log\n",
    "                    </option>\n",
    "\n",
    "                </select>\n",
    "\n",
    "            </div>\n",
    "\n",
    "\n",
    "            <div class=\"control-group\">\n",
    "\n",
    "                <label for=\"searchBox\">\n",
    "                    Search active table\n",
    "                </label>\n",
    "\n",
    "                <input\n",
    "                    type=\"text\"\n",
    "                    id=\"searchBox\"\n",
    "                    placeholder=\"Search file name, UID or value...\"\n",
    "                >\n",
    "\n",
    "            </div>\n",
    "\n",
    "\n",
    "            <button\n",
    "                type=\"button\"\n",
    "                id=\"clearSearchButton\"\n",
    "            >\n",
    "                Clear Search\n",
    "            </button>\n",
    "\n",
    "        </div>\n",
    "\n",
    "\n",
    "        <div class=\"content-card\">\n",
    "\n",
    "            <div class=\"table-title\">\n",
    "\n",
    "                <h2 id=\"activeTableTitle\">\n",
    "                    Paraffin\n",
    "                </h2>\n",
    "\n",
    "                <div\n",
    "                    id=\"tableCounter\"\n",
    "                    class=\"table-counter\"\n",
    "                >\n",
    "                </div>\n",
    "\n",
    "            </div>\n",
    "\n",
    "\n",
    "            <div class=\"table-scroll\">\n",
    "\n",
    "                <div\n",
    "                    id=\"Paraffin\"\n",
    "                    class=\"table-container active\"\n",
    "                >\n",
    "                    {tables_html[\"Paraffin\"]}\n",
    "                </div>\n",
    "\n",
    "\n",
    "                <div\n",
    "                    id=\"I-Paraffins\"\n",
    "                    class=\"table-container\"\n",
    "                >\n",
    "                    {tables_html[\"I-Paraffins\"]}\n",
    "                </div>\n",
    "\n",
    "\n",
    "                <div\n",
    "                    id=\"Aromatics\"\n",
    "                    class=\"table-container\"\n",
    "                >\n",
    "                    {tables_html[\"Aromatics\"]}\n",
    "                </div>\n",
    "\n",
    "\n",
    "                <div\n",
    "                    id=\"Naphthenes\"\n",
    "                    class=\"table-container\"\n",
    "                >\n",
    "                    {tables_html[\"Naphthenes\"]}\n",
    "                </div>\n",
    "\n",
    "\n",
    "                <div\n",
    "                    id=\"Olefins\"\n",
    "                    class=\"table-container\"\n",
    "                >\n",
    "                    {tables_html[\"Olefins\"]}\n",
    "                </div>\n",
    "\n",
    "\n",
    "                <div\n",
    "                    id=\"Metadata\"\n",
    "                    class=\"table-container\"\n",
    "                >\n",
    "                    {metadata_html}\n",
    "                </div>\n",
    "\n",
    "\n",
    "                <div\n",
    "                    id=\"Processing-Log\"\n",
    "                    class=\"table-container\"\n",
    "                >\n",
    "                    {processing_log_html}\n",
    "                </div>\n",
    "\n",
    "\n",
    "                <div\n",
    "                    id=\"noResultsMessage\"\n",
    "                    class=\"message\"\n",
    "                >\n",
    "                    No matching records were found.\n",
    "                </div>\n",
    "\n",
    "            </div>\n",
    "\n",
    "        </div>\n",
    "\n",
    "\n",
    "        <div class=\"footer\">\n",
    "\n",
    "            Source folder:\n",
    "            {folder_path}\n",
    "\n",
    "        </div>\n",
    "\n",
    "    </div>\n",
    "\n",
    "\n",
    "    <script>\n",
    "\n",
    "        const componentSelector =\n",
    "            document.getElementById(\"componentSelector\");\n",
    "\n",
    "        const searchBox =\n",
    "            document.getElementById(\"searchBox\");\n",
    "\n",
    "        const clearSearchButton =\n",
    "            document.getElementById(\"clearSearchButton\");\n",
    "\n",
    "        const activeTableTitle =\n",
    "            document.getElementById(\"activeTableTitle\");\n",
    "\n",
    "        const tableCounter =\n",
    "            document.getElementById(\"tableCounter\");\n",
    "\n",
    "        const noResultsMessage =\n",
    "            document.getElementById(\"noResultsMessage\");\n",
    "\n",
    "\n",
    "        function getActiveContainer() {{\n",
    "\n",
    "            return document.querySelector(\n",
    "                \".table-container.active\"\n",
    "            );\n",
    "        }}\n",
    "\n",
    "\n",
    "        function updateCounter() {{\n",
    "\n",
    "            const activeContainer = getActiveContainer();\n",
    "\n",
    "            if (!activeContainer) {{\n",
    "                tableCounter.textContent = \"\";\n",
    "                return;\n",
    "            }}\n",
    "\n",
    "            const rows = activeContainer.querySelectorAll(\n",
    "                \"tbody tr\"\n",
    "            );\n",
    "\n",
    "            let visibleRows = 0;\n",
    "\n",
    "            rows.forEach(function(row) {{\n",
    "\n",
    "                if (!row.classList.contains(\"hidden-row\")) {{\n",
    "                    visibleRows += 1;\n",
    "                }}\n",
    "\n",
    "            }});\n",
    "\n",
    "            tableCounter.textContent =\n",
    "                visibleRows + \" of \" + rows.length + \" records\";\n",
    "\n",
    "            if (rows.length > 0 && visibleRows === 0) {{\n",
    "                noResultsMessage.classList.add(\"visible\");\n",
    "            }}\n",
    "            else {{\n",
    "                noResultsMessage.classList.remove(\"visible\");\n",
    "            }}\n",
    "        }}\n",
    "\n",
    "\n",
    "        function filterActiveTable() {{\n",
    "\n",
    "            const filterText =\n",
    "                searchBox.value.trim().toLowerCase();\n",
    "\n",
    "            const activeContainer = getActiveContainer();\n",
    "\n",
    "            if (!activeContainer) {{\n",
    "                return;\n",
    "            }}\n",
    "\n",
    "            const rows = activeContainer.querySelectorAll(\n",
    "                \"tbody tr\"\n",
    "            );\n",
    "\n",
    "            rows.forEach(function(row) {{\n",
    "\n",
    "                const rowText =\n",
    "                    row.textContent.toLowerCase();\n",
    "\n",
    "                if (\n",
    "                    filterText === \"\" ||\n",
    "                    rowText.includes(filterText)\n",
    "                ) {{\n",
    "                    row.classList.remove(\"hidden-row\");\n",
    "                }}\n",
    "                else {{\n",
    "                    row.classList.add(\"hidden-row\");\n",
    "                }}\n",
    "\n",
    "            }});\n",
    "\n",
    "            updateCounter();\n",
    "        }}\n",
    "\n",
    "\n",
    "        componentSelector.addEventListener(\n",
    "            \"change\",\n",
    "            function() {{\n",
    "\n",
    "                document\n",
    "                    .querySelectorAll(\".table-container\")\n",
    "                    .forEach(function(container) {{\n",
    "\n",
    "                        container.classList.remove(\"active\");\n",
    "\n",
    "                        container\n",
    "                            .querySelectorAll(\"tbody tr\")\n",
    "                            .forEach(function(row) {{\n",
    "                                row.classList.remove(\"hidden-row\");\n",
    "                            }});\n",
    "\n",
    "                    }});\n",
    "\n",
    "                const selectedContainer =\n",
    "                    document.getElementById(this.value);\n",
    "\n",
    "                if (selectedContainer) {{\n",
    "                    selectedContainer.classList.add(\"active\");\n",
    "                }}\n",
    "\n",
    "                activeTableTitle.textContent =\n",
    "                    this.options[this.selectedIndex].text;\n",
    "\n",
    "                searchBox.value = \"\";\n",
    "\n",
    "                noResultsMessage.classList.remove(\"visible\");\n",
    "\n",
    "                updateCounter();\n",
    "\n",
    "            }}\n",
    "        );\n",
    "\n",
    "\n",
    "        searchBox.addEventListener(\n",
    "            \"input\",\n",
    "            filterActiveTable\n",
    "        );\n",
    "\n",
    "\n",
    "        clearSearchButton.addEventListener(\n",
    "            \"click\",\n",
    "            function() {{\n",
    "\n",
    "                searchBox.value = \"\";\n",
    "\n",
    "                filterActiveTable();\n",
    "\n",
    "                searchBox.focus();\n",
    "\n",
    "            }}\n",
    "        );\n",
    "\n",
    "\n",
    "        updateCounter();\n",
    "\n",
    "    </script>\n",
    "\n",
    "</body>\n",
    "\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 16. WRITE THE HTML FILE\n",
    "# ============================================================\n",
    "\n",
    "with open(\n",
    "    html_file,\n",
    "    mode=\"w\",\n",
    "    encoding=\"utf-8\",\n",
    ") as html_output:\n",
    "\n",
    "    html_output.write(html_content)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 17. FINAL PROCESSING SUMMARY\n",
    "# ============================================================\n",
    "\n",
    "successful_files = 0\n",
    "failed_files = 0\n",
    "\n",
    "if not processing_log_df.empty:\n",
    "\n",
    "    successful_files = int(\n",
    "        processing_log_df[\"Status\"]\n",
    "        .eq(\"Success\")\n",
    "        .sum()\n",
    "    )\n",
    "\n",
    "    failed_files = int(\n",
    "        processing_log_df[\"Status\"]\n",
    "        .eq(\"Failed\")\n",
    "        .sum()\n",
    "    )\n",
    "\n",
    "\n",
    "print()\n",
    "print(\"=\" * 75)\n",
    "print(\"PROCESSING COMPLETED\")\n",
    "print(\"=\" * 75)\n",
    "print(f\"Total XLS files found : {len(xls_files)}\")\n",
    "print(f\"Successfully processed: {successful_files}\")\n",
    "print(f\"Failed files          : {failed_files}\")\n",
    "print()\n",
    "print(\"HTML file created at:\")\n",
    "print(html_file.resolve())\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 18. AUTOMATICALLY OPEN THE HTML FILE\n",
    "# ============================================================\n",
    "\n",
    "try:\n",
    "    webbrowser.open(html_file.resolve().as_uri())\n",
    "    print()\n",
    "    print(\"The HTML dashboard was opened in your default browser.\")\n",
    "\n",
    "except Exception as browser_error:\n",
    "    print()\n",
    "    print(\n",
    "        \"The HTML file was created, but it could not be \"\n",
    "        \"opened automatically.\"\n",
    "    )\n",
    "    print(f\"Browser error: {browser_error}\")\n",
    "    print(\"Manually double-click the HTML file shown above.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
