const $=s=>document.querySelector(s);let r1=[],r2=[],r3=[],c2=[],reactorRows=[],active='table1';
const comps=['Paraffin','I-Paraffins','Aromatics','Naphthenes','Olefins','Unknown'];
const c1=['File Name','UID','DateTime','Component','Active Reactor',...Array.from({length:15},(_,i)=>`C${i+1}`),'Unknowns'];
const c3=['File Name','UID','DateTime','TOS(h)','Active Reactor','Lin-RON','Lin-MON','Cal-RON','Cal-MON'];
const reactorCols=['DateTime','R1','R2','R3','R4','R5','R6','R7','R8'];
const showError=(m='')=>{const x=$('#error');x.textContent=m;x.classList.toggle('show',!!m)};
const selected=()=>new Set([...document.querySelectorAll('#filterMenu input:checked')].map(x=>x.value));
const fmt=v=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(2):(v??'');
function parseDateTime(value){const text=String(value??'').trim(),match=text.match(/^(\d{2})\/(\d{2})\/(\d{4})[ T](\d{2}):(\d{2})(?::(\d{2}))?$/);if(match)return new Date(Number(match[3]),Number(match[2])-1,Number(match[1]),Number(match[4]),Number(match[5]),Number(match[6]||0)).getTime();const iso=Date.parse(text.replace(' ','T'));return Number.isNaN(iso)?null:iso}
function activeReactorAt(value){const sampleTime=parseDateTime(value);if(sampleTime===null)return '';const timeline=reactorRows.map(row=>({time:parseDateTime(row.DateTime),row})).filter(x=>x.time!==null).sort((a,b)=>a.time-b.time);for(let i=0;i<timeline.length-1;i+=1){if(timeline[i].time<=sampleTime&&sampleTime<timeline[i+1].time)return reactorCols.slice(1).filter(column=>Number(timeline[i].row[column])===1).join(', ')}return ''}
function withTos(rows){let cumulative=0.0,prevTime=null;return rows.map((row,idx)=>{if(row['TOS(h)']!==undefined&&row['TOS(h)']!==null&&row['TOS(h)']!=='')return row;const t=parseDateTime(row.DateTime);let tos=0.0;if(idx===0){tos=0.0;prevTime=t;}else if(t!==null&&prevTime!==null){const diff=(t-prevTime)/3600000;cumulative+=diff;tos=Math.round(cumulative*100)/100;prevTime=t;}else{tos=0.0;}return {...row,'TOS(h)':tos};});}
function render(){const withReactor=row=>({...row,'Active Reactor':activeReactorAt(row.DateTime)});let rows=active==='table1'?r1.map(withReactor):active==='table2'?r2.map(withReactor):withTos(r3).map(withReactor),cols=active==='table1'?c1:active==='table2'?c2:c3,q=$('#search').value.toLowerCase(),selectedReactor=$('#reactorFilter')?$('#reactorFilter').value:'';if(active==='table1'){const s=selected();rows=rows.filter(x=>s.has(x.Component))}if(selectedReactor){rows=rows.filter(x=>{const ar=String(x['Active Reactor']||'').trim();if(selectedReactor==='__none__')return !ar;return ar.split(',').map(s=>s.trim()).includes(selectedReactor)})}rows=rows.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q));const rLabel=selectedReactor==='__none__'?'None':(selectedReactor||'All');if(active==='table1'){const s=selected();$('#filterSummary').textContent=`Showing ${[...s].join(', ')||'no components'} · Active Reactor: ${rLabel}`;$('#filterSummary').style.display='block'}else if(active==='table3'){$('#filterSummary').textContent=`Octane Table · Active Reactor: ${rLabel}`;$('#filterSummary').style.display=selectedReactor?'block':'none'}else if(active==='table2'){$('#filterSummary').textContent=`Component List · Active Reactor: ${rLabel}`;$('#filterSummary').style.display=selectedReactor?'block':'none'}else{$('#filterSummary').style.display='none'}$('#componentFilter').style.display=active==='table1'?'block':'none';if($('#reactorFilterWrap'))$('#reactorFilterWrap').style.display=active==='reactorMap'?'none':'block';$('#dataTable').className=`${active}-table`;$(`#thead`).innerHTML=cols.map(x=>`<th>${x}</th>`).join('');$('#tbody').innerHTML=rows.map(x=>`<tr>${cols.map(k=>`<td>${fmt(x[k])}</td>`).join('')}</tr>`).join('');$('#empty').style.display=rows.length?'none':'block'}
function activate(name){active=name;document.querySelectorAll('.table-tab').forEach(x=>{const on=x.dataset.table===name;x.classList.toggle('active',on);x.setAttribute('aria-selected',String(on))});const reactor=name==='reactorMap';$('#dataTablePanel').hidden=reactor;$('#reactorMapPanel').hidden=!reactor;if(reactor){restoreDashboardState();renderReactorMap();$('#status').textContent='Reactor Map';return}const meta={table1:['DHA DATA · TABLE-1','Carbon-number table'],table2:['DHA DATA · TABLE-2','Component-list table'],table3:['DHA DATA · TABLE-3','Octane Table']}[name];$('#tableEyebrow').textContent=meta[0];$('#tableTitle').textContent=meta[1];$('#status').textContent='Ready';render()}
function kpis(s){const x=[['Files found',s.files_found],['Table-1 processed',s.table1_processed],['Table-2 processed',s.table2_processed],['Table-3 processed',s.table3_processed]];$('#kpis').innerHTML=x.map(a=>`<div class="kpi"><span>${a[0]}</span><b>${a[1]}</b></div>`).join('')}
async function getJson(r){const t=await r.text();try{return JSON.parse(t)}catch{throw Error('Server returned an invalid response. Restart the updated dashboard.')}}
function reactorDateTimeValue(value){return value ? value.replace(' ','T') : ''}
function renderReactorMap(){const from=$('#valveFrom').value,to=$('#valveTo').value;let rows=reactorRows.filter(x=>(!from||reactorDateTimeValue(x.DateTime)>=from)&&(!to||reactorDateTimeValue(x.DateTime)<=to));$('#reactorThead').innerHTML=reactorCols.map(x=>`<th>${x}</th>`).join('');$('#reactorTbody').innerHTML=rows.map(x=>`<tr><td>${x.DateTime}</td>${reactorCols.slice(1).map(k=>`<td><span class="reactor-dot ${x[k]===1?'open':'closed'}"></span></td>`).join('')}</tr>`).join('');$('#reactorEmpty').style.display=rows.length?'none':'block';$('#reactorCount').textContent=`${rows.length} of ${reactorRows.length} five-minute records`}
function restoreDashboardState(){try{const saved=JSON.parse(sessionStorage.getItem('dhaDashboardState')||localStorage.getItem('dhaDashboardState')||'null');if(saved){if(Array.isArray(saved.r1))r1=saved.r1;if(Array.isArray(saved.r2))r2=saved.r2;if(Array.isArray(saved.r3))r3=withTos(saved.r3);if(Array.isArray(saved.reactorRows))reactorRows=saved.reactorRows;if(Array.isArray(saved.c2))c2=saved.c2;if(saved.selectedReactor&&$('#reactorFilter'))$('#reactorFilter').value=saved.selectedReactor;if(saved.summary)kpis(saved.summary);if(saved.valveFrom&&$('#valveFrom'))$('#valveFrom').value=saved.valveFrom;if(saved.valveTo&&$('#valveTo'))$('#valveTo').value=saved.valveTo}const shared=JSON.parse(sessionStorage.getItem('dhaDateTimeFilter')||'null');if(shared){if(shared.from&&$('#valveFrom'))$('#valveFrom').value=shared.from;if(shared.to&&$('#valveTo'))$('#valveTo').value=shared.to}}catch(e){sessionStorage.removeItem('dhaDashboardState')}}
function saveDashboardState(summary){let saved=null;try{saved=JSON.parse(sessionStorage.getItem('dhaDashboardState')||localStorage.getItem('dhaDashboardState')||'null')}catch(e){}const from=$('#valveFrom')?.value||'',to=$('#valveTo')?.value||'',state=JSON.stringify({r1,r2,r3,c2,reactorRows,selectedReactor:$('#reactorFilter')?.value||'',summary:summary||saved?.summary||null,valveFrom:from,valveTo:to});sessionStorage.setItem('dhaDashboardState',state);localStorage.setItem('dhaDashboardState',state);sessionStorage.setItem('dhaDateTimeFilter',JSON.stringify({from,to}))}
async function init(){restoreDashboardState();try{let r=await fetch('/api/settings'),d=await getJson(r);$('#folder').value=d.default_source_directory;$('#reactorFolder').value=d.default_reactor_source_directory||''}catch(e){showError(e.message)}render()}
document.querySelectorAll('.table-tab').forEach(x=>x.onclick=()=>activate(x.dataset.table));
$('#filterButton').onclick=e=>{e.stopPropagation();$('#filterMenu').classList.toggle('open')};$('#filterMenu').onclick=e=>e.stopPropagation();document.addEventListener('click',()=>$('#filterMenu').classList.remove('open'));document.querySelectorAll('#filterMenu input').forEach(x=>x.onchange=render);$('#selectAllComponents').onclick=()=>{document.querySelectorAll('#filterMenu input').forEach(x=>x.checked=true);render()};$('#clearComponents').onclick=()=>{document.querySelectorAll('#filterMenu input').forEach(x=>x.checked=false);render()};
$('#browse').onclick=async()=>{const btn=$('#browse');if(btn.disabled)return;showError();const old=btn.textContent;btn.disabled=true;btn.textContent='Browsing...';try{let r=await fetch('/api/browse-folder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initial_directory:$('#folder').value})}),d=await getJson(r);if(!r.ok)throw Error(d.error);if(!d.cancelled&&d.path)$('#folder').value=d.path}catch(e){showError(e.message)}finally{btn.disabled=false;btn.textContent=old}};
$('#process').onclick=async()=>{const runNum=(sessionStorage.getItem('ils_run_number')||localStorage.getItem('ils_run_number')||'').trim();if(!runNum){showError("Please enter run number to start with");return}showError();$('#status').textContent='Processing...';$('#process').disabled=true;try{let r=await fetch('/api/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:$('#folder').value})}),d=await getJson(r);if(!r.ok)throw Error(d.error);r1=d.rows||[];r2=d.table2_rows||[];r3=withTos(d.table3_rows||[]);c2=d.table2_columns||[];kpis(d.summary);saveDashboardState(d.summary);render();const summary=d.summary||{};const firstError=(d.processing_log||[]).find(x=>x.Status==='Failed'||x.Message);if(!summary.files_found)showError('No .XLS files found in the selected folder.');else if(!summary.processed)showError(firstError?.Message||'All discovered XLS files failed to process.');else if(firstError)showError(`Some files could not be processed: ${firstError['File Name']} · ${firstError.Message}`);$('#status').textContent=summary.processed?'Ready':'Failed'}catch(e){showError(e.message);$('#status').textContent='Failed'}finally{$('#process').disabled=false}};
$('#reactorBrowse').onclick=async()=>{const btn=$('#reactorBrowse');if(btn.disabled)return;showError();const old=btn.textContent;btn.disabled=true;btn.textContent='Browsing...';try{let r=await fetch('/api/browse-reactor-folder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initial_directory:$('#reactorFolder').value})}),d=await getJson(r);if(!r.ok)throw Error(d.error);if(!d.cancelled&&d.path)$('#reactorFolder').value=d.path}catch(e){showError(e.message)}finally{btn.disabled=false;btn.textContent=old}};
$('#reactorProcess').onclick=async()=>{const runNum=(sessionStorage.getItem('ils_run_number')||localStorage.getItem('ils_run_number')||'').trim();if(!runNum){showError("Please enter run number to start with");return}showError();$('#status').textContent='Processing Reactor Map...';$('#reactorProcess').disabled=true;try{let r=await fetch('/api/process-reactor-map',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:$('#reactorFolder').value})}),d=await getJson(r);if(!r.ok)throw Error(d.error);reactorRows=d.rows;$('#valveFrom').value=reactorDateTimeValue(d.minimum_datetime);$('#valveTo').value=reactorDateTimeValue(d.maximum_datetime);$('#valveFrom').min=reactorDateTimeValue(d.minimum_datetime);$('#valveFrom').max=reactorDateTimeValue(d.maximum_datetime);$('#valveTo').min=reactorDateTimeValue(d.minimum_datetime);$('#valveTo').max=reactorDateTimeValue(d.maximum_datetime);saveDashboardState();renderReactorMap();render();$('#status').textContent='Reactor Map Ready'}catch(e){showError(e.message);$('#status').textContent='Failed'}finally{$('#reactorProcess').disabled=false}};
$('#valveFrom').oninput=()=>{saveDashboardState();renderReactorMap()};$('#valveTo').oninput=()=>{saveDashboardState();renderReactorMap()};$('#search').oninput=render;if($('#reactorFilter'))$('#reactorFilter').onchange=()=>{saveDashboardState();render()};init();
