const $=s=>document.querySelector(s);let r1=[],r2=[],r3=[],c2=[],reactorRows=[],active='table1';
const comps=['Paraffin','I-Paraffins','Aromatics','Naphthenes','Olefins','Unknown'];
const c1=['File Name','UID','DateTime','Component','Active Reactor',...Array.from({length:15},(_,i)=>`C${i+1}`),'Unknowns'];
const c3=['File Name','UID','DateTime','Lin-RON','Lin-MON','Cal-RON','Cal-MON'];
const reactorCols=['DateTime','R1','R2','R3','R4','R5','R6','R7','R8'];
const showError=(m='')=>{const x=$('#error');x.textContent=m;x.classList.toggle('show',!!m)};
const selected=()=>new Set([...document.querySelectorAll('#filterMenu input:checked')].map(x=>x.value));
const fmt=v=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(2):(v??'');
function parseDateTime(value){const text=String(value??'').trim(),match=text.match(/^(\d{2})\/(\d{2})\/(\d{4})[ T](\d{2}):(\d{2})(?::(\d{2}))?$/);if(match)return new Date(Number(match[3]),Number(match[2])-1,Number(match[1]),Number(match[4]),Number(match[5]),Number(match[6]||0)).getTime();const iso=Date.parse(text.replace(' ','T'));return Number.isNaN(iso)?null:iso}
function activeReactorAt(value){const sampleTime=parseDateTime(value);if(sampleTime===null)return '';const timeline=reactorRows.map(row=>({time:parseDateTime(row.DateTime),row})).filter(x=>x.time!==null).sort((a,b)=>a.time-b.time);for(let i=0;i<timeline.length-1;i+=1){if(timeline[i].time<=sampleTime&&sampleTime<timeline[i+1].time)return reactorCols.slice(1).filter(column=>Number(timeline[i].row[column])===1).join(', ')}return ''}
function render(){let rows=active==='table1'?r1.map(row=>({...row,'Active Reactor':activeReactorAt(row.DateTime)})):active==='table2'?r2:r3,cols=active==='table1'?c1:active==='table2'?c2:c3,q=$('#search').value.toLowerCase();if(active==='table1'){const s=selected();rows=rows.filter(x=>s.has(x.Component));$('#filterSummary').textContent=`Showing ${[...s].join(', ')||'no components'}`}rows=rows.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q));$('#componentFilter').style.display=active==='table1'?'block':'none';$('#filterSummary').style.display=active==='table1'?'block':'none';$('#dataTable').className=`${active}-table`;$(`#thead`).innerHTML=cols.map(x=>`<th>${x}</th>`).join('');$('#tbody').innerHTML=rows.map(x=>`<tr>${cols.map(k=>`<td>${fmt(x[k])}</td>`).join('')}</tr>`).join('');$('#empty').style.display=rows.length?'none':'block'}
function activate(name){active=name;document.querySelectorAll('.table-tab').forEach(x=>{const on=x.dataset.table===name;x.classList.toggle('active',on);x.setAttribute('aria-selected',String(on))});const reactor=name==='reactorMap';$('#dataTablePanel').hidden=reactor;$('#reactorMapPanel').hidden=!reactor;if(reactor){renderReactorMap();$('#status').textContent='Reactor Map';return}const meta={table1:['DHA DATA · TABLE-1','Carbon-number table'],table2:['DHA DATA · TABLE-2','Component-list table'],table3:['DHA DATA · TABLE-3','Octane Table']}[name];$('#tableEyebrow').textContent=meta[0];$('#tableTitle').textContent=meta[1];$('#status').textContent='Ready';render()}
function kpis(s){const x=[['Files found',s.files_found],['Table-1 processed',s.table1_processed],['Table-2 processed',s.table2_processed],['Table-3 processed',s.table3_processed]];$('#kpis').innerHTML=x.map(a=>`<div class="kpi"><span>${a[0]}</span><b>${a[1]}</b></div>`).join('')}
async function getJson(r){const t=await r.text();try{return JSON.parse(t)}catch{throw Error('Server returned an invalid response. Restart the updated dashboard.')}}
function reactorDateTimeValue(value){return value ? value.replace(' ','T') : ''}
function renderReactorMap(){const from=$('#valveFrom').value,to=$('#valveTo').value;let rows=reactorRows.filter(x=>(!from||reactorDateTimeValue(x.DateTime)>=from)&&(!to||reactorDateTimeValue(x.DateTime)<=to));$('#reactorThead').innerHTML=reactorCols.map(x=>`<th>${x}</th>`).join('');$('#reactorTbody').innerHTML=rows.map(x=>`<tr><td>${x.DateTime}</td>${reactorCols.slice(1).map(k=>`<td><span class="reactor-dot ${x[k]===1?'open':'closed'}"></span></td>`).join('')}</tr>`).join('');$('#reactorEmpty').style.display=rows.length?'none':'block';$('#reactorCount').textContent=`${rows.length} of ${reactorRows.length} five-minute records`}
function restoreDashboardState(){try{const saved=JSON.parse(sessionStorage.getItem('dhaDashboardState')||'null');if(!saved)return;if(Array.isArray(saved.r1))r1=saved.r1;if(Array.isArray(saved.r2))r2=saved.r2;if(Array.isArray(saved.r3))r3=saved.r3;if(Array.isArray(saved.reactorRows))reactorRows=saved.reactorRows;if(Array.isArray(saved.c2))c2=saved.c2;if(saved.summary)kpis(saved.summary)}catch(e){sessionStorage.removeItem('dhaDashboardState')}}
function saveDashboardState(summary){let saved=null;try{saved=JSON.parse(sessionStorage.getItem('dhaDashboardState')||'null')}catch(e){}sessionStorage.setItem('dhaDashboardState',JSON.stringify({r1,r2,r3,c2,reactorRows,summary:summary||saved?.summary||null}))}
async function init(){restoreDashboardState();try{let r=await fetch('/api/settings'),d=await getJson(r);$('#folder').value=d.default_source_directory;$('#reactorFolder').value=d.default_reactor_source_directory||''}catch(e){showError(e.message)}render()}
document.querySelectorAll('.table-tab').forEach(x=>x.onclick=()=>activate(x.dataset.table));
$('#filterButton').onclick=e=>{e.stopPropagation();$('#filterMenu').classList.toggle('open')};$('#filterMenu').onclick=e=>e.stopPropagation();document.addEventListener('click',()=>$('#filterMenu').classList.remove('open'));document.querySelectorAll('#filterMenu input').forEach(x=>x.onchange=render);$('#selectAllComponents').onclick=()=>{document.querySelectorAll('#filterMenu input').forEach(x=>x.checked=true);render()};$('#clearComponents').onclick=()=>{document.querySelectorAll('#filterMenu input').forEach(x=>x.checked=false);render()};
$('#browse').onclick=async()=>{showError();try{let r=await fetch('/api/browse-folder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initial_directory:$('#folder').value})}),d=await getJson(r);if(!r.ok)throw Error(d.error);$('#folder').value=d.path}catch(e){showError(e.message)}};
$('#process').onclick=async()=>{showError();$('#status').textContent='Processing...';$('#process').disabled=true;try{let r=await fetch('/api/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:$('#folder').value})}),d=await getJson(r);if(!r.ok)throw Error(d.error);r1=d.rows;r2=d.table2_rows;r3=d.table3_rows;c2=d.table2_columns;kpis(d.summary);saveDashboardState(d.summary);render();$('#status').textContent='Ready'}catch(e){showError(e.message);$('#status').textContent='Failed'}finally{$('#process').disabled=false}};
$('#reactorBrowse').onclick=async()=>{showError();try{let r=await fetch('/api/browse-reactor-folder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initial_directory:$('#reactorFolder').value})}),d=await getJson(r);if(!r.ok)throw Error(d.error);$('#reactorFolder').value=d.path}catch(e){showError(e.message)}};
$('#reactorProcess').onclick=async()=>{showError();$('#status').textContent='Processing Reactor Map...';$('#reactorProcess').disabled=true;try{let r=await fetch('/api/process-reactor-map',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:$('#reactorFolder').value})}),d=await getJson(r);if(!r.ok)throw Error(d.error);reactorRows=d.rows;saveDashboardState();$('#valveFrom').value=reactorDateTimeValue(d.minimum_datetime);$('#valveTo').value=reactorDateTimeValue(d.maximum_datetime);$('#valveFrom').min=reactorDateTimeValue(d.minimum_datetime);$('#valveFrom').max=reactorDateTimeValue(d.maximum_datetime);$('#valveTo').min=reactorDateTimeValue(d.minimum_datetime);$('#valveTo').max=reactorDateTimeValue(d.maximum_datetime);renderReactorMap();render();$('#status').textContent='Reactor Map Ready'}catch(e){showError(e.message);$('#status').textContent='Failed'}finally{$('#reactorProcess').disabled=false}};
$('#valveFrom').oninput=renderReactorMap;$('#valveTo').oninput=renderReactorMap;$('#search').oninput=render;init();
